In [15]:
import numpy as np
import pandas as pd


import warnings
warnings.filterwarnings(action='ignore')

In [17]:
a=[10,20,30,40]
print(type(a))

<class 'list'>


In [22]:
a2=np.array(a)
print(type(a2))

<class 'numpy.ndarray'>


In [19]:
print(type(a2))

<class 'numpy.ndarray'>


In [5]:
a=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(a))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
arr=np.array([[1,2,3],[10,11,12]])


In [24]:
print(arr)

[[ 1  2  3]
 [10 11 12]]


In [25]:
np.max(arr)

np.int64(12)

In [26]:
np.min(arr)

np.int64(1)

In [27]:
np.sum(arr)

np.int64(39)

In [28]:
np.mean(arr)

np.float64(6.5)

In [29]:
a1=np.zeros((3,3))
a2=np.ones((3,3))
print(a1)
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
# pandas 

print(pd.Series(a,index=['a','b','c']))

a    [1, 2, 3]
b    [4, 5, 6]
c    [7, 8, 9]
dtype: object


In [28]:
data=[10,20,30]
df=pd.DataFrame(data)
df

0
0  10
1  20
2  30

In [33]:
# Creating dataFrame using the dictionary

d={'Rollno':[12,13,14],'Name':['Paliwnder','Abhinav','Eakam'],'Stream':['Genai','DS','ML']}
df2=pd.DataFrame(d,index=[1,2,3])
df2

Rollno       Name Stream
1      12  Paliwnder  Genai
2      13    Abhinav     DS
3      14      Eakam     ML

In [35]:
l=[[12,'Palwinder',20],[15,'Abhinav',22]]
df3=pd.DataFrame(l,columns=['Rollno','Name','Age'])
df3

Rollno       Name  Age
0      12  Palwinder   20
1      15    Abhinav   22

In [39]:
df2

Rollno       Name Stream
1      12  Paliwnder  Genai
2      13    Abhinav     DS
3      14      Eakam     ML

In [47]:
df2.loc[1] # location based

Rollno           12
Name      Paliwnder
Stream        Genai
Name: 1, dtype: object

In [48]:
df2.iloc[:,:]

Rollno       Name Stream
1      12  Paliwnder  Genai
2      13    Abhinav     DS
3      14      Eakam     ML

In [53]:
df2.iloc[1:3,-1]

2    DS
3    ML
Name: Stream, dtype: object

In [1]:
import pandas as pd