In [2]:
import pandas as pd 
from sklearn.datasets import make_classification


In [3]:
data= make_classification(n_samples=1000,n_features=10,n_classes=2, random_state=10)

In [4]:
x,y= data

In [5]:
x[0]

array([-1.00583777, -0.37653943, -0.62017967, -0.15756653, -1.12080531,
       -0.58909086, -1.57457766,  1.67804613,  1.0801799 ,  0.35358714])

In [6]:
y[0]

np.int64(0)

In [7]:
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression 

In [8]:
x_train,x_test, y_train,y_test= train_test_split(x,y)

In [9]:
len(x_train)

750

In [10]:
x_test

array([[-6.21494653e-02, -1.41099511e-01,  7.75097675e-01, ...,
         2.55216283e-01, -1.14558650e-01, -1.12608741e+00],
       [ 4.39125125e-01,  4.49444740e-01,  3.79342687e-01, ...,
        -1.44637398e+00,  2.34685232e+00, -2.36841627e+00],
       [ 5.29759347e-01, -1.73623198e+00, -6.28954924e-02, ...,
        -2.28713511e+00, -2.16612924e+00,  1.25119912e-01],
       ...,
       [ 5.31338679e-01,  7.61875566e-01, -3.73090044e-02, ...,
        -2.13204404e+00,  5.04508361e-02, -7.60716534e-01],
       [ 2.00963126e-03, -1.08085205e+00, -2.53563404e-02, ...,
        -7.01600716e-02,  5.58380239e-01,  3.97658820e-01],
       [-1.62396894e-01, -1.31050947e+00,  1.27937055e+00, ...,
         5.70774236e-01, -5.16289792e-01, -1.24727339e+00]],
      shape=(250, 10))

In [11]:
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred= model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score 

In [13]:
confusion_matrix(y_pred, y_test)

array([[120,  15],
       [ 11, 104]])

In [22]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.92      0.89      0.90       135
           1       0.87      0.90      0.89       115

    accuracy                           0.90       250
   macro avg       0.89      0.90      0.90       250
weighted avg       0.90      0.90      0.90       250



In [15]:
accuracy_score(y_pred, y_test)

0.896

In [16]:
x1,y1= make_classification(n_samples=10,n_classes=2,n_features=10)

In [17]:
y1_pred= model.predict(x1)

In [18]:
y1

array([1, 1, 1, 0, 0, 1, 0, 1, 0, 0])

In [19]:
accuracy_score(y1,y1_pred)

0.5

In [20]:
x1

array([[ 0.78489991, -0.30073351, -0.73124896, -0.34206886,  0.67786477,
        -0.27530005, -1.28369321, -1.23374904,  0.9380906 ,  0.72632263],
       [-0.53047921, -1.59251142, -0.83452927,  0.01396683, -0.06359328,
         0.17004759, -0.23808995, -1.23330422,  1.65665363, -0.82935651],
       [-0.06464222,  0.5837347 , -0.99188862,  0.68249262, -0.56915739,
         0.81683592, -1.10194335,  0.29880791,  0.9840122 , -0.33585712],
       [-0.1824058 , -0.69388239, -0.42840211,  0.46996458, -0.75736871,
         0.49686899, -0.10364568,  0.73605702, -0.02260878, -0.44824523],
       [ 0.91631797,  0.77894822, -1.44121527,  0.37350942,  1.09309386,
         0.29749858,  0.38905468,  1.37224593, -1.05745425,  1.16036173],
       [ 0.55153432,  1.7900069 ,  0.02403136, -0.06223432,  0.24667723,
         0.08992782,  1.03300013, -1.35623692,  1.66505532, -1.00062284],
       [-0.1337462 ,  0.43982975,  0.08039117,  0.67440193,  0.54287568,
         0.76119122, -0.37103694,  0.66678389

In [21]:
x[1]

array([ 0.41117999,  0.76240872, -0.78421   , -0.09647917, -0.40875846,
       -0.66578006,  0.21094182, -0.85044853, -0.46130068,  1.06223729])