# NLP Natural Language Processing jisme ham human data ko machine data mein convert karna
## Machine data is of the form of Vector Embeddings


In [28]:
# Stop words : is am are . 
# tf-idf vecorizer , count vectorizers
# tokenization
# Stemmin an Lemmatization 
# Bag of Words


In [29]:
import nltk
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('punkt_tab')

In [30]:
import pandas as pd
data = {
    "text": [
        "I love this product",
        "This is a 23523@# bad product. This is very poor product",
        "Amazing experience. I would love to buy it again",
        "Worst service ever. donot buy it, i am gonna give it -1 star",
        "I am very $#  happy",
        "I am very disappointed   2    "
    ],
    "label": [1, 0, 1, 0, 1, 0]   # 1 = Positive, 0 = Negative
}

df = pd.DataFrame(data)
df

,text,label
0,I love this product,1
1,This is a 23523@# bad product. This is very po...,0
2,Amazing experience. I would love to buy it again,1
3,"Worst service ever. donot buy it, i am gonna g...",0
4,I am very $# happy,1
5,I am very disappointed 2,0


In [31]:
# Text Cleaning

import re

def clean_text(text):
    text = text.lower()                  # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text)        # remove extra spaces
    return text

df['clean_text'] = df['text'].apply(clean_text)
print(df[['text', 'clean_text']])

                                                text  \
0                                I love this product   
1  This is a 23523@# bad product. This is very po...   
2   Amazing experience. I would love to buy it again   
3  Worst service ever. donot buy it, i am gonna g...   
4                                I am very $#  happy   
5                     I am very disappointed   2       

                                          clean_text  
0                                i love this product  
1    this is a bad product this is very poor product  
2    amazing experience i would love to buy it again  
3  worst service ever donot buy it i am gonna giv...  
4                                    i am very happy  
5                            i am very disappointed   


In [32]:
df

,text,label,clean_text
0,I love this product,1,i love this product
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...
4,I am very $# happy,1,i am very happy
5,I am very disappointed 2,0,i am very disappointed


In [33]:
# Tokenization 
'''  1. Word Tokenization
     2. Sentence Tokenization
     3. Character tokeniztion
'''

from nltk.tokenize import word_tokenize

df['tokens'] = df['clean_text'].apply(word_tokenize)
print(df['tokens'])
df

0                             [i, love, this, product]
1    [this, is, a, bad, product, this, is, very, po...
2    [amazing, experience, i, would, love, to, buy,...
3    [worst, service, ever, donot, buy, it, i, am, ...
4                                 [i, am, very, happy]
5                          [i, am, very, disappointed]
Name: tokens, dtype: object


,text,label,clean_text,tokens
0,I love this product,1,i love this product,"[i, love, this, product]"
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po..."
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,..."
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ..."
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]"
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]"


In [34]:
from nltk.tokenize import sent_tokenize
df['sentence_tokens']=df['clean_text'].apply(sent_tokenize)

In [35]:
print(df['sentence_tokens'])
df

0                                [i love this product]
1    [this is a bad product this is very poor product]
2    [amazing experience i would love to buy it again]
3    [worst service ever donot buy it i am gonna gi...
4                                    [i am very happy]
5                             [i am very disappointed]
Name: sentence_tokens, dtype: object


,text,label,clean_text,tokens,sentence_tokens
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product]
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product]
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again]
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy]
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed]


In [36]:
# charaacter tokenization
a="palwinder"
n=len(a)
l=[]
for i in range(n):
    l.append(a[i])
print(l)

['p', 'a', 'l', 'w', 'i', 'n', 'd', 'e', 'r']


In [37]:
# after getting the cleaned text and proper tokens we will perform the stopwords removal
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['no_stopwords'] = df['tokens'].apply(remove_stopwords)
print(df['no_stopwords'])

0                                      [love, product]
1                        [bad, product, poor, product]
2              [amazing, experience, would, love, buy]
3    [worst, service, ever, donot, buy, gon, na, gi...
4                                              [happy]
5                                       [disappointed]
Name: no_stopwords, dtype: object


In [38]:
df

,text,label,clean_text,tokens,sentence_tokens,no_stopwords
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product],"[love, product]"
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product],"[bad, product, poor, product]"
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again],"[amazing, experience, would, love, buy]"
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...,"[worst, service, ever, donot, buy, gon, na, gi..."
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy],[happy]
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed],[disappointed]


In [39]:
# stemming 
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stemming(tokens):
    return [stemmer.stem(word) for word in tokens]

df['stemmed'] = df['no_stopwords'].apply(stemming)
print(df['stemmed'])

0                                      [love, product]
1                        [bad, product, poor, product]
2                     [amaz, experi, would, love, buy]
3    [worst, servic, ever, donot, buy, gon, na, giv...
4                                              [happi]
5                                         [disappoint]
Name: stemmed, dtype: object


In [40]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatized'] = df['no_stopwords'].apply(lemmatization)
print(df['lemmatized'])

0                                      [love, product]
1                        [bad, product, poor, product]
2              [amazing, experience, would, love, buy]
3    [worst, service, ever, donot, buy, gon, na, gi...
4                                              [happy]
5                                       [disappointed]
Name: lemmatized, dtype: object


In [41]:
df['final_text'] = df['lemmatized'].apply(lambda x: " ".join(x))
print(df['final_text'])

0                                     love product
1                         bad product poor product
2                amazing experience would love buy
3    worst service ever donot buy gon na give star
4                                            happy
5                                     disappointed
Name: final_text, dtype: str


In [42]:
df

,text,label,clean_text,tokens,sentence_tokens,no_stopwords,stemmed,lemmatized,final_text
0,I love this product,1,i love this product,"[i, love, this, product]",[i love this product],"[love, product]","[love, product]","[love, product]",love product
1,This is a 23523@# bad product. This is very po...,0,this is a bad product this is very poor product,"[this, is, a, bad, product, this, is, very, po...",[this is a bad product this is very poor product],"[bad, product, poor, product]","[bad, product, poor, product]","[bad, product, poor, product]",bad product poor product
2,Amazing experience. I would love to buy it again,1,amazing experience i would love to buy it again,"[amazing, experience, i, would, love, to, buy,...",[amazing experience i would love to buy it again],"[amazing, experience, would, love, buy]","[amaz, experi, would, love, buy]","[amazing, experience, would, love, buy]",amazing experience would love buy
3,"Worst service ever. donot buy it, i am gonna g...",0,worst service ever donot buy it i am gonna giv...,"[worst, service, ever, donot, buy, it, i, am, ...",[worst service ever donot buy it i am gonna gi...,"[worst, service, ever, donot, buy, gon, na, gi...","[worst, servic, ever, donot, buy, gon, na, giv...","[worst, service, ever, donot, buy, gon, na, gi...",worst service ever donot buy gon na give star
4,I am very $# happy,1,i am very happy,"[i, am, very, happy]",[i am very happy],[happy],[happi],[happy],happy
5,I am very disappointed 2,0,i am very disappointed,"[i, am, very, disappointed]",[i am very disappointed],[disappointed],[disappoint],[disappointed],disappointed


In [43]:
df.drop(columns=['text','clean_text','tokens','sentence_tokens','no_stopwords','stemmed','lemmatized'])

,label,final_text
0,1,love product
1,0,bad product poor product
2,1,amazing experience would love buy
3,0,worst service ever donot buy gon na give star
4,1,happy
5,0,disappointed


In [44]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(df['final_text']).toarray()
y = df['label']

print("Vocabulary:", cv.vocabulary_)
print("Feature Matrix:\n", X)


Vocabulary: {'love': 10, 'product': 13, 'bad': 1, 'poor': 12, 'amazing': 0, 'experience': 6, 'would': 17, 'buy': 2, 'worst': 16, 'service': 14, 'ever': 5, 'donot': 4, 'gon': 8, 'na': 11, 'give': 7, 'star': 15, 'happy': 9, 'disappointed': 3}
Feature Matrix:
 [[0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0]
 [1 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1]
 [0 0 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [45]:
#TF-IDF vectorizer === Termed Frequency Inverse document frequency vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['final_text']).toarray()

In [46]:
print(X)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.70710678 0.
  0.         0.70710678 0.         0.         0.         0.        ]
 [0.         0.46177217 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.46177217 0.75731957 0.         0.         0.         0.        ]
 [0.47974754 0.         0.39339985 0.         0.         0.
  0.47974754 0.         0.         0.         0.39339985 0.
  0.         0.         0.         0.         0.         0.47974754]
 [0.         0.         0.27845254 0.         0.33957035 0.33957035
  0.         0.33957035 0.33957035 0.         0.         0.33957035
  0.         0.         0.33957035 0.33957035 0.33957035 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         1.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.  

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,df.label,test_size=0.2)

In [48]:
x_train

array([[0.        , 0.        , 0.27845254, 0.        , 0.33957035,
        0.33957035, 0.        , 0.33957035, 0.33957035, 0.        ,
        0.        , 0.33957035, 0.        , 0.        , 0.33957035,
        0.33957035, 0.33957035, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.70710678, 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [49]:
lr=LogisticRegression()

In [50]:
lr.fit(x_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [51]:
y_test

1    0
2    1
Name: label, dtype: int64

In [52]:
y_pred=lr.predict(x_test)

In [53]:
y_pred


array([1, 1])

In [ ]:
querry=input("User inputL: ")


def predict(querry):
    querry=clean_text(querry)
    tokens=word_tokenize(querry)
    # stop words removal

    lematized=' '.join([lemmatizer])
    # vectorizer
    # prediction 
    #return predicted value
    